server:
  port: 8773

spring:
  application:
    name: service-client2
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
